services:
  postgres17_auth_db:
    image: postgres:17
    container_name: postgres17_auth_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: "authentication_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "@admin1"
    ports:
      - "5432:5432"
    volumes:
      - ./01_create_scheme_auth.sql:/docker-entrypoint-initdb.d/01_create_scheme_auth.sql
      - postgres17_auth_db:/var/lib/postgresql/data

  pgadmin4:
    image: elestio/pgadmin:REL-9_6
    container_name: pgadminREL_9_6_db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8088:8080"

volumes:
  postgres17_auth_db:
