server:
  port: 8080
spring:
  application:
    name: "authentication-msvc"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
routes:
  paths:
    users: "/api/v1/users"
    userByDocumentNumber: "/api/v1/users/{documentNumber}"
    userByEmail: "/api/v1/users/email/{email}"
    usersByEmails: "/api/v1/users/emails/batch"
    auth:
      login: "/api/v1/login"
adapters:
  r2dbc:
    host: ${AUTH_MSVC_DB_HOST:postgres17_auth_db}
    port: ${AUTH_MSVC_DB_PORT:5432}
    database: ${AUTH_MSVC_DB_DATABASE:authentication_db}
    schema: ${AUTH_MSVC_DB_SCHEMA:public}
    username: ${AUTH_MSVC_DB_USERNAME:admin}
    password: ${AUTH_MSVC_DB_PASSWORD:@admin1}
security:
  jwt:
    secretKey: ${SUPER_SECRET_KEY:"VC_ayQoxqq_7BcqwcYplfPc5Au38nbm8Z_u5ReEHVE0="}
    expiration: ${JWT_EXPIRATION:3600}
